/* Generated interrupt stubs + low-level entry points. */
.section .text

.global isr0
isr0:
    pushq $0
    pushq $0
    jmp isr_common
.global isr1
isr1:
    pushq $0
    pushq $1
    jmp isr_common
.global isr2
isr2:
    pushq $0
    pushq $2
    jmp isr_common
.global isr3
isr3:
    pushq $0
    pushq $3
    jmp isr_common
.global isr4
isr4:
    pushq $0
    pushq $4
    jmp isr_common
.global isr5
isr5:
    pushq $0
    pushq $5
    jmp isr_common
.global isr6
isr6:
    pushq $0
    pushq $6
    jmp isr_common
.global isr7
isr7:
    pushq $0
    pushq $7
    jmp isr_common
.global isr8
isr8:
    pushq $8
    jmp isr_common
.global isr9
isr9:
    pushq $0
    pushq $9
    jmp isr_common
.global isr10
isr10:
    pushq $10
    jmp isr_common
.global isr11
isr11:
    pushq $11
    jmp isr_common
.global isr12
isr12:
    pushq $12
    jmp isr_common
.global isr13
isr13:
    pushq $13
    jmp isr_common
.global isr14
isr14:
    pushq $14
    jmp isr_common
.global isr15
isr15:
    pushq $0
    pushq $15
    jmp isr_common
.global isr16
isr16:
    pushq $0
    pushq $16
    jmp isr_common
.global isr17
isr17:
    pushq $17
    jmp isr_common
.global isr18
isr18:
    pushq $0
    pushq $18
    jmp isr_common
.global isr19
isr19:
    pushq $0
    pushq $19
    jmp isr_common
.global isr20
isr20:
    pushq $0
    pushq $20
    jmp isr_common
.global isr21
isr21:
    pushq $21
    jmp isr_common
.global isr22
isr22:
    pushq $0
    pushq $22
    jmp isr_common
.global isr23
isr23:
    pushq $0
    pushq $23
    jmp isr_common
.global isr24
isr24:
    pushq $0
    pushq $24
    jmp isr_common
.global isr25
isr25:
    pushq $0
    pushq $25
    jmp isr_common
.global isr26
isr26:
    pushq $0
    pushq $26
    jmp isr_common
.global isr27
isr27:
    pushq $0
    pushq $27
    jmp isr_common
.global isr28
isr28:
    pushq $0
    pushq $28
    jmp isr_common
.global isr29
isr29:
    pushq $29
    jmp isr_common
.global isr30
isr30:
    pushq $30
    jmp isr_common
.global isr31
isr31:
    pushq $0
    pushq $31
    jmp isr_common
.global isr32
isr32:
    pushq $0
    pushq $32
    jmp isr_common
.global isr33
isr33:
    pushq $0
    pushq $33
    jmp isr_common
.global isr34
isr34:
    pushq $0
    pushq $34
    jmp isr_common
.global isr35
isr35:
    pushq $0
    pushq $35
    jmp isr_common
.global isr36
isr36:
    pushq $0
    pushq $36
    jmp isr_common
.global isr37
isr37:
    pushq $0
    pushq $37
    jmp isr_common
.global isr38
isr38:
    pushq $0
    pushq $38
    jmp isr_common
.global isr39
isr39:
    pushq $0
    pushq $39
    jmp isr_common
.global isr40
isr40:
    pushq $0
    pushq $40
    jmp isr_common
.global isr41
isr41:
    pushq $0
    pushq $41
    jmp isr_common
.global isr42
isr42:
    pushq $0
    pushq $42
    jmp isr_common
.global isr43
isr43:
    pushq $0
    pushq $43
    jmp isr_common
.global isr44
isr44:
    pushq $0
    pushq $44
    jmp isr_common
.global isr45
isr45:
    pushq $0
    pushq $45
    jmp isr_common
.global isr46
isr46:
    pushq $0
    pushq $46
    jmp isr_common
.global isr47
isr47:
    pushq $0
    pushq $47
    jmp isr_common
.global isr48
isr48:
    pushq $0
    pushq $48
    jmp isr_common
.global isr49
isr49:
    pushq $0
    pushq $49
    jmp isr_common
.global isr50
isr50:
    pushq $0
    pushq $50
    jmp isr_common
.global isr51
isr51:
    pushq $0
    pushq $51
    jmp isr_common
.global isr52
isr52:
    pushq $0
    pushq $52
    jmp isr_common
.global isr53
isr53:
    pushq $0
    pushq $53
    jmp isr_common
.global isr54
isr54:
    pushq $0
    pushq $54
    jmp isr_common
.global isr55
isr55:
    pushq $0
    pushq $55
    jmp isr_common
.global isr56
isr56:
    pushq $0
    pushq $56
    jmp isr_common
.global isr57
isr57:
    pushq $0
    pushq $57
    jmp isr_common
.global isr58
isr58:
    pushq $0
    pushq $58
    jmp isr_common
.global isr59
isr59:
    pushq $0
    pushq $59
    jmp isr_common
.global isr60
isr60:
    pushq $0
    pushq $60
    jmp isr_common
.global isr61
isr61:
    pushq $0
    pushq $61
    jmp isr_common
.global isr62
isr62:
    pushq $0
    pushq $62
    jmp isr_common
.global isr63
isr63:
    pushq $0
    pushq $63
    jmp isr_common
.global isr64
isr64:
    pushq $0
    pushq $64
    jmp isr_common
.global isr65
isr65:
    pushq $0
    pushq $65
    jmp isr_common
.global isr66
isr66:
    pushq $0
    pushq $66
    jmp isr_common
.global isr67
isr67:
    pushq $0
    pushq $67
    jmp isr_common
.global isr68
isr68:
    pushq $0
    pushq $68
    jmp isr_common
.global isr69
isr69:
    pushq $0
    pushq $69
    jmp isr_common
.global isr70
isr70:
    pushq $0
    pushq $70
    jmp isr_common
.global isr71
isr71:
    pushq $0
    pushq $71
    jmp isr_common
.global isr72
isr72:
    pushq $0
    pushq $72
    jmp isr_common
.global isr73
isr73:
    pushq $0
    pushq $73
    jmp isr_common
.global isr74
isr74:
    pushq $0
    pushq $74
    jmp isr_common
.global isr75
isr75:
    pushq $0
    pushq $75
    jmp isr_common
.global isr76
isr76:
    pushq $0
    pushq $76
    jmp isr_common
.global isr77
isr77:
    pushq $0
    pushq $77
    jmp isr_common
.global isr78
isr78:
    pushq $0
    pushq $78
    jmp isr_common
.global isr79
isr79:
    pushq $0
    pushq $79
    jmp isr_common
.global isr80
isr80:
    pushq $0
    pushq $80
    jmp isr_common
.global isr81
isr81:
    pushq $0
    pushq $81
    jmp isr_common
.global isr82
isr82:
    pushq $0
    pushq $82
    jmp isr_common
.global isr83
isr83:
    pushq $0
    pushq $83
    jmp isr_common
.global isr84
isr84:
    pushq $0
    pushq $84
    jmp isr_common
.global isr85
isr85:
    pushq $0
    pushq $85
    jmp isr_common
.global isr86
isr86:
    pushq $0
    pushq $86
    jmp isr_common
.global isr87
isr87:
    pushq $0
    pushq $87
    jmp isr_common
.global isr88
isr88:
    pushq $0
    pushq $88
    jmp isr_common
.global isr89
isr89:
    pushq $0
    pushq $89
    jmp isr_common
.global isr90
isr90:
    pushq $0
    pushq $90
    jmp isr_common
.global isr91
isr91:
    pushq $0
    pushq $91
    jmp isr_common
.global isr92
isr92:
    pushq $0
    pushq $92
    jmp isr_common
.global isr93
isr93:
    pushq $0
    pushq $93
    jmp isr_common
.global isr94
isr94:
    pushq $0
    pushq $94
    jmp isr_common
.global isr95
isr95:
    pushq $0
    pushq $95
    jmp isr_common
.global isr96
isr96:
    pushq $0
    pushq $96
    jmp isr_common
.global isr97
isr97:
    pushq $0
    pushq $97
    jmp isr_common
.global isr98
isr98:
    pushq $0
    pushq $98
    jmp isr_common
.global isr99
isr99:
    pushq $0
    pushq $99
    jmp isr_common
.global isr100
isr100:
    pushq $0
    pushq $100
    jmp isr_common
.global isr101
isr101:
    pushq $0
    pushq $101
    jmp isr_common
.global isr102
isr102:
    pushq $0
    pushq $102
    jmp isr_common
.global isr103
isr103:
    pushq $0
    pushq $103
    jmp isr_common
.global isr104
isr104:
    pushq $0
    pushq $104
    jmp isr_common
.global isr105
isr105:
    pushq $0
    pushq $105
    jmp isr_common
.global isr106
isr106:
    pushq $0
    pushq $106
    jmp isr_common
.global isr107
isr107:
    pushq $0
    pushq $107
    jmp isr_common
.global isr108
isr108:
    pushq $0
    pushq $108
    jmp isr_common
.global isr109
isr109:
    pushq $0
    pushq $109
    jmp isr_common
.global isr110
isr110:
    pushq $0
    pushq $110
    jmp isr_common
.global isr111
isr111:
    pushq $0
    pushq $111
    jmp isr_common
.global isr112
isr112:
    pushq $0
    pushq $112
    jmp isr_common
.global isr113
isr113:
    pushq $0
    pushq $113
    jmp isr_common
.global isr114
isr114:
    pushq $0
    pushq $114
    jmp isr_common
.global isr115
isr115:
    pushq $0
    pushq $115
    jmp isr_common
.global isr116
isr116:
    pushq $0
    pushq $116
    jmp isr_common
.global isr117
isr117:
    pushq $0
    pushq $117
    jmp isr_common
.global isr118
isr118:
    pushq $0
    pushq $118
    jmp isr_common
.global isr119
isr119:
    pushq $0
    pushq $119
    jmp isr_common
.global isr120
isr120:
    pushq $0
    pushq $120
    jmp isr_common
.global isr121
isr121:
    pushq $0
    pushq $121
    jmp isr_common
.global isr122
isr122:
    pushq $0
    pushq $122
    jmp isr_common
.global isr123
isr123:
    pushq $0
    pushq $123
    jmp isr_common
.global isr124
isr124:
    pushq $0
    pushq $124
    jmp isr_common
.global isr125
isr125:
    pushq $0
    pushq $125
    jmp isr_common
.global isr126
isr126:
    pushq $0
    pushq $126
    jmp isr_common
.global isr127
isr127:
    pushq $0
    pushq $127
    jmp isr_common
.global isr128
isr128:
    pushq $0
    pushq $128
    jmp isr_common
.global isr129
isr129:
    pushq $0
    pushq $129
    jmp isr_common
.global isr130
isr130:
    pushq $0
    pushq $130
    jmp isr_common
.global isr131
isr131:
    pushq $0
    pushq $131
    jmp isr_common
.global isr132
isr132:
    pushq $0
    pushq $132
    jmp isr_common
.global isr133
isr133:
    pushq $0
    pushq $133
    jmp isr_common
.global isr134
isr134:
    pushq $0
    pushq $134
    jmp isr_common
.global isr135
isr135:
    pushq $0
    pushq $135
    jmp isr_common
.global isr136
isr136:
    pushq $0
    pushq $136
    jmp isr_common
.global isr137
isr137:
    pushq $0
    pushq $137
    jmp isr_common
.global isr138
isr138:
    pushq $0
    pushq $138
    jmp isr_common
.global isr139
isr139:
    pushq $0
    pushq $139
    jmp isr_common
.global isr140
isr140:
    pushq $0
    pushq $140
    jmp isr_common
.global isr141
isr141:
    pushq $0
    pushq $141
    jmp isr_common
.global isr142
isr142:
    pushq $0
    pushq $142
    jmp isr_common
.global isr143
isr143:
    pushq $0
    pushq $143
    jmp isr_common
.global isr144
isr144:
    pushq $0
    pushq $144
    jmp isr_common
.global isr145
isr145:
    pushq $0
    pushq $145
    jmp isr_common
.global isr146
isr146:
    pushq $0
    pushq $146
    jmp isr_common
.global isr147
isr147:
    pushq $0
    pushq $147
    jmp isr_common
.global isr148
isr148:
    pushq $0
    pushq $148
    jmp isr_common
.global isr149
isr149:
    pushq $0
    pushq $149
    jmp isr_common
.global isr150
isr150:
    pushq $0
    pushq $150
    jmp isr_common
.global isr151
isr151:
    pushq $0
    pushq $151
    jmp isr_common
.global isr152
isr152:
    pushq $0
    pushq $152
    jmp isr_common
.global isr153
isr153:
    pushq $0
    pushq $153
    jmp isr_common
.global isr154
isr154:
    pushq $0
    pushq $154
    jmp isr_common
.global isr155
isr155:
    pushq $0
    pushq $155
    jmp isr_common
.global isr156
isr156:
    pushq $0
    pushq $156
    jmp isr_common
.global isr157
isr157:
    pushq $0
    pushq $157
    jmp isr_common
.global isr158
isr158:
    pushq $0
    pushq $158
    jmp isr_common
.global isr159
isr159:
    pushq $0
    pushq $159
    jmp isr_common
.global isr160
isr160:
    pushq $0
    pushq $160
    jmp isr_common
.global isr161
isr161:
    pushq $0
    pushq $161
    jmp isr_common
.global isr162
isr162:
    pushq $0
    pushq $162
    jmp isr_common
.global isr163
isr163:
    pushq $0
    pushq $163
    jmp isr_common
.global isr164
isr164:
    pushq $0
    pushq $164
    jmp isr_common
.global isr165
isr165:
    pushq $0
    pushq $165
    jmp isr_common
.global isr166
isr166:
    pushq $0
    pushq $166
    jmp isr_common
.global isr167
isr167:
    pushq $0
    pushq $167
    jmp isr_common
.global isr168
isr168:
    pushq $0
    pushq $168
    jmp isr_common
.global isr169
isr169:
    pushq $0
    pushq $169
    jmp isr_common
.global isr170
isr170:
    pushq $0
    pushq $170
    jmp isr_common
.global isr171
isr171:
    pushq $0
    pushq $171
    jmp isr_common
.global isr172
isr172:
    pushq $0
    pushq $172
    jmp isr_common
.global isr173
isr173:
    pushq $0
    pushq $173
    jmp isr_common
.global isr174
isr174:
    pushq $0
    pushq $174
    jmp isr_common
.global isr175
isr175:
    pushq $0
    pushq $175
    jmp isr_common
.global isr176
isr176:
    pushq $0
    pushq $176
    jmp isr_common
.global isr177
isr177:
    pushq $0
    pushq $177
    jmp isr_common
.global isr178
isr178:
    pushq $0
    pushq $178
    jmp isr_common
.global isr179
isr179:
    pushq $0
    pushq $179
    jmp isr_common
.global isr180
isr180:
    pushq $0
    pushq $180
    jmp isr_common
.global isr181
isr181:
    pushq $0
    pushq $181
    jmp isr_common
.global isr182
isr182:
    pushq $0
    pushq $182
    jmp isr_common
.global isr183
isr183:
    pushq $0
    pushq $183
    jmp isr_common
.global isr184
isr184:
    pushq $0
    pushq $184
    jmp isr_common
.global isr185
isr185:
    pushq $0
    pushq $185
    jmp isr_common
.global isr186
isr186:
    pushq $0
    pushq $186
    jmp isr_common
.global isr187
isr187:
    pushq $0
    pushq $187
    jmp isr_common
.global isr188
isr188:
    pushq $0
    pushq $188
    jmp isr_common
.global isr189
isr189:
    pushq $0
    pushq $189
    jmp isr_common
.global isr190
isr190:
    pushq $0
    pushq $190
    jmp isr_common
.global isr191
isr191:
    pushq $0
    pushq $191
    jmp isr_common
.global isr192
isr192:
    pushq $0
    pushq $192
    jmp isr_common
.global isr193
isr193:
    pushq $0
    pushq $193
    jmp isr_common
.global isr194
isr194:
    pushq $0
    pushq $194
    jmp isr_common
.global isr195
isr195:
    pushq $0
    pushq $195
    jmp isr_common
.global isr196
isr196:
    pushq $0
    pushq $196
    jmp isr_common
.global isr197
isr197:
    pushq $0
    pushq $197
    jmp isr_common
.global isr198
isr198:
    pushq $0
    pushq $198
    jmp isr_common
.global isr199
isr199:
    pushq $0
    pushq $199
    jmp isr_common
.global isr200
isr200:
    pushq $0
    pushq $200
    jmp isr_common
.global isr201
isr201:
    pushq $0
    pushq $201
    jmp isr_common
.global isr202
isr202:
    pushq $0
    pushq $202
    jmp isr_common
.global isr203
isr203:
    pushq $0
    pushq $203
    jmp isr_common
.global isr204
isr204:
    pushq $0
    pushq $204
    jmp isr_common
.global isr205
isr205:
    pushq $0
    pushq $205
    jmp isr_common
.global isr206
isr206:
    pushq $0
    pushq $206
    jmp isr_common
.global isr207
isr207:
    pushq $0
    pushq $207
    jmp isr_common
.global isr208
isr208:
    pushq $0
    pushq $208
    jmp isr_common
.global isr209
isr209:
    pushq $0
    pushq $209
    jmp isr_common
.global isr210
isr210:
    pushq $0
    pushq $210
    jmp isr_common
.global isr211
isr211:
    pushq $0
    pushq $211
    jmp isr_common
.global isr212
isr212:
    pushq $0
    pushq $212
    jmp isr_common
.global isr213
isr213:
    pushq $0
    pushq $213
    jmp isr_common
.global isr214
isr214:
    pushq $0
    pushq $214
    jmp isr_common
.global isr215
isr215:
    pushq $0
    pushq $215
    jmp isr_common
.global isr216
isr216:
    pushq $0
    pushq $216
    jmp isr_common
.global isr217
isr217:
    pushq $0
    pushq $217
    jmp isr_common
.global isr218
isr218:
    pushq $0
    pushq $218
    jmp isr_common
.global isr219
isr219:
    pushq $0
    pushq $219
    jmp isr_common
.global isr220
isr220:
    pushq $0
    pushq $220
    jmp isr_common
.global isr221
isr221:
    pushq $0
    pushq $221
    jmp isr_common
.global isr222
isr222:
    pushq $0
    pushq $222
    jmp isr_common
.global isr223
isr223:
    pushq $0
    pushq $223
    jmp isr_common
.global isr224
isr224:
    pushq $0
    pushq $224
    jmp isr_common
.global isr225
isr225:
    pushq $0
    pushq $225
    jmp isr_common
.global isr226
isr226:
    pushq $0
    pushq $226
    jmp isr_common
.global isr227
isr227:
    pushq $0
    pushq $227
    jmp isr_common
.global isr228
isr228:
    pushq $0
    pushq $228
    jmp isr_common
.global isr229
isr229:
    pushq $0
    pushq $229
    jmp isr_common
.global isr230
isr230:
    pushq $0
    pushq $230
    jmp isr_common
.global isr231
isr231:
    pushq $0
    pushq $231
    jmp isr_common
.global isr232
isr232:
    pushq $0
    pushq $232
    jmp isr_common
.global isr233
isr233:
    pushq $0
    pushq $233
    jmp isr_common
.global isr234
isr234:
    pushq $0
    pushq $234
    jmp isr_common
.global isr235
isr235:
    pushq $0
    pushq $235
    jmp isr_common
.global isr236
isr236:
    pushq $0
    pushq $236
    jmp isr_common
.global isr237
isr237:
    pushq $0
    pushq $237
    jmp isr_common
.global isr238
isr238:
    pushq $0
    pushq $238
    jmp isr_common
.global isr239
isr239:
    pushq $0
    pushq $239
    jmp isr_common
.global isr240
isr240:
    pushq $0
    pushq $240
    jmp isr_common
.global isr241
isr241:
    pushq $0
    pushq $241
    jmp isr_common
.global isr242
isr242:
    pushq $0
    pushq $242
    jmp isr_common
.global isr243
isr243:
    pushq $0
    pushq $243
    jmp isr_common
.global isr244
isr244:
    pushq $0
    pushq $244
    jmp isr_common
.global isr245
isr245:
    pushq $0
    pushq $245
    jmp isr_common
.global isr246
isr246:
    pushq $0
    pushq $246
    jmp isr_common
.global isr247
isr247:
    pushq $0
    pushq $247
    jmp isr_common
.global isr248
isr248:
    pushq $0
    pushq $248
    jmp isr_common
.global isr249
isr249:
    pushq $0
    pushq $249
    jmp isr_common
.global isr250
isr250:
    pushq $0
    pushq $250
    jmp isr_common
.global isr251
isr251:
    pushq $0
    pushq $251
    jmp isr_common
.global isr252
isr252:
    pushq $0
    pushq $252
    jmp isr_common
.global isr253
isr253:
    pushq $0
    pushq $253
    jmp isr_common
.global isr254
isr254:
    pushq $0
    pushq $254
    jmp isr_common
.global isr255
isr255:
    pushq $0
    pushq $255
    jmp isr_common

isr_common:
    cmpq $0x08, 24(%rsp)
    je 1f
    swapgs
1:
    pushq %rax
    pushq %rbx
    pushq %rcx
    pushq %rdx
    pushq %rsi
    pushq %rdi
    pushq %rbp
    pushq %r8
    pushq %r9
    pushq %r10
    pushq %r11
    pushq %r12
    pushq %r13
    pushq %r14
    pushq %r15
    movq %rsp, %rdi
    cld
    call interrupt_dispatch
.global isr_return
isr_return:
    popq %r15
    popq %r14
    popq %r13
    popq %r12
    popq %r11
    popq %r10
    popq %r9
    popq %r8
    popq %rbp
    popq %rdi
    popq %rsi
    popq %rdx
    popq %rcx
    popq %rbx
    popq %rax
    cmpq $0x08, 24(%rsp)
    je 2f
    swapgs
2:
    addq $16, %rsp
    iretq

/* void gdt_load(const GdtPtr *ptr) */
.global gdt_load
gdt_load:
    lgdt (%rdi)
    movw $0x10, %ax
    movw %ax, %ds
    movw %ax, %es
    movw %ax, %ss
    xorw %ax, %ax
    movw %ax, %fs
    movw %ax, %gs
    popq %rdi
    pushq $0x08
    pushq %rdi
    lretq

/* void switch_context(u64 *old_rsp, u64 new_rsp) */
.global switch_context
switch_context:
    pushq %rbp
    pushq %rbx
    pushq %r12
    pushq %r13
    pushq %r14
    pushq %r15
    movq %rsp, (%rdi)
    movq %rsi, %rsp
    popq %r15
    popq %r14
    popq %r13
    popq %r12
    popq %rbx
    popq %rbp
    ret

/* first switch into a kernel thread: r12 = entry, r13 = arg */
.global kthread_trampoline
kthread_trampoline:
    andq $-16, %rsp
    call sched_thread_start
    movq %r13, %rdi
    call *%r12
    call sched_kthread_exit
    ud2

/* first switch into a thread that returns to user mode: rsp -> TrapFrame */
.global uthread_trampoline
uthread_trampoline:
    movq %rsp, %rbx
    andq $-16, %rsp
    call sched_thread_start
    movq %rbx, %rsp
    jmp isr_return


/* Linux-style `syscall` entry. Builds a TrapFrame identical to the interrupt
 * path (vector 0x80) and always returns through iretq. */
.global syscall_entry
syscall_entry:
    swapgs
    movq %rsp, %gs:16
    movq %gs:8, %rsp
    pushq $0x1b
    pushq %gs:16
    pushq %r11
    pushq $0x23
    pushq %rcx
    pushq $0
    pushq $0x80
    pushq %rax
    pushq %rbx
    pushq %rcx
    pushq %rdx
    pushq %rsi
    pushq %rdi
    pushq %rbp
    pushq %r8
    pushq %r9
    pushq %r10
    pushq %r11
    pushq %r12
    pushq %r13
    pushq %r14
    pushq %r15
    movq %rsp, %rdi
    cld
    sti
    call syscall_dispatch
    cli
    jmp isr_return

.section .rodata
.global isr_table
isr_table:
    .quad isr0
    .quad isr1
    .quad isr2
    .quad isr3
    .quad isr4
    .quad isr5
    .quad isr6
    .quad isr7
    .quad isr8
    .quad isr9
    .quad isr10
    .quad isr11
    .quad isr12
    .quad isr13
    .quad isr14
    .quad isr15
    .quad isr16
    .quad isr17
    .quad isr18
    .quad isr19
    .quad isr20
    .quad isr21
    .quad isr22
    .quad isr23
    .quad isr24
    .quad isr25
    .quad isr26
    .quad isr27
    .quad isr28
    .quad isr29
    .quad isr30
    .quad isr31
    .quad isr32
    .quad isr33
    .quad isr34
    .quad isr35
    .quad isr36
    .quad isr37
    .quad isr38
    .quad isr39
    .quad isr40
    .quad isr41
    .quad isr42
    .quad isr43
    .quad isr44
    .quad isr45
    .quad isr46
    .quad isr47
    .quad isr48
    .quad isr49
    .quad isr50
    .quad isr51
    .quad isr52
    .quad isr53
    .quad isr54
    .quad isr55
    .quad isr56
    .quad isr57
    .quad isr58
    .quad isr59
    .quad isr60
    .quad isr61
    .quad isr62
    .quad isr63
    .quad isr64
    .quad isr65
    .quad isr66
    .quad isr67
    .quad isr68
    .quad isr69
    .quad isr70
    .quad isr71
    .quad isr72
    .quad isr73
    .quad isr74
    .quad isr75
    .quad isr76
    .quad isr77
    .quad isr78
    .quad isr79
    .quad isr80
    .quad isr81
    .quad isr82
    .quad isr83
    .quad isr84
    .quad isr85
    .quad isr86
    .quad isr87
    .quad isr88
    .quad isr89
    .quad isr90
    .quad isr91
    .quad isr92
    .quad isr93
    .quad isr94
    .quad isr95
    .quad isr96
    .quad isr97
    .quad isr98
    .quad isr99
    .quad isr100
    .quad isr101
    .quad isr102
    .quad isr103
    .quad isr104
    .quad isr105
    .quad isr106
    .quad isr107
    .quad isr108
    .quad isr109
    .quad isr110
    .quad isr111
    .quad isr112
    .quad isr113
    .quad isr114
    .quad isr115
    .quad isr116
    .quad isr117
    .quad isr118
    .quad isr119
    .quad isr120
    .quad isr121
    .quad isr122
    .quad isr123
    .quad isr124
    .quad isr125
    .quad isr126
    .quad isr127
    .quad isr128
    .quad isr129
    .quad isr130
    .quad isr131
    .quad isr132
    .quad isr133
    .quad isr134
    .quad isr135
    .quad isr136
    .quad isr137
    .quad isr138
    .quad isr139
    .quad isr140
    .quad isr141
    .quad isr142
    .quad isr143
    .quad isr144
    .quad isr145
    .quad isr146
    .quad isr147
    .quad isr148
    .quad isr149
    .quad isr150
    .quad isr151
    .quad isr152
    .quad isr153
    .quad isr154
    .quad isr155
    .quad isr156
    .quad isr157
    .quad isr158
    .quad isr159
    .quad isr160
    .quad isr161
    .quad isr162
    .quad isr163
    .quad isr164
    .quad isr165
    .quad isr166
    .quad isr167
    .quad isr168
    .quad isr169
    .quad isr170
    .quad isr171
    .quad isr172
    .quad isr173
    .quad isr174
    .quad isr175
    .quad isr176
    .quad isr177
    .quad isr178
    .quad isr179
    .quad isr180
    .quad isr181
    .quad isr182
    .quad isr183
    .quad isr184
    .quad isr185
    .quad isr186
    .quad isr187
    .quad isr188
    .quad isr189
    .quad isr190
    .quad isr191
    .quad isr192
    .quad isr193
    .quad isr194
    .quad isr195
    .quad isr196
    .quad isr197
    .quad isr198
    .quad isr199
    .quad isr200
    .quad isr201
    .quad isr202
    .quad isr203
    .quad isr204
    .quad isr205
    .quad isr206
    .quad isr207
    .quad isr208
    .quad isr209
    .quad isr210
    .quad isr211
    .quad isr212
    .quad isr213
    .quad isr214
    .quad isr215
    .quad isr216
    .quad isr217
    .quad isr218
    .quad isr219
    .quad isr220
    .quad isr221
    .quad isr222
    .quad isr223
    .quad isr224
    .quad isr225
    .quad isr226
    .quad isr227
    .quad isr228
    .quad isr229
    .quad isr230
    .quad isr231
    .quad isr232
    .quad isr233
    .quad isr234
    .quad isr235
    .quad isr236
    .quad isr237
    .quad isr238
    .quad isr239
    .quad isr240
    .quad isr241
    .quad isr242
    .quad isr243
    .quad isr244
    .quad isr245
    .quad isr246
    .quad isr247
    .quad isr248
    .quad isr249
    .quad isr250
    .quad isr251
    .quad isr252
    .quad isr253
    .quad isr254
    .quad isr255
